In [2]:
import os
os.listdir()

['Untitled.ipynb',
 'supermarkets.json',
 'supermarkets.csv',
 'supermarkets-semi-colons.txt',
 'supermarkets.xlsx',
 '.ipynb_checkpoints',
 'supermarkets-commas.txt']

In [1]:
import pandas

In [3]:
df=pandas.read_csv("supermarkets.csv")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [4]:
df=pandas.read_json("supermarkets.json")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [5]:
df=pandas.read_excel("supermarkets.xlsx",sheet_name=0)
df

,ID,Address,City,State,Country,Supermarket Name,Number of Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [8]:
df=pandas.read_csv("supermarkets-commas.txt")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [14]:
df=pandas.read_csv("supermarkets-semi-colons.txt", sep=";")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [33]:
df = pandas.read_csv("data.txt", header=None)
df

   0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [34]:
df.columns = ["ID", "Address", "City", "ZIP", "Country", "Name", "Employees"]
df

,ID,Address,City,ZIP,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [35]:
df.set_index("ID")

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [36]:
df

,ID,Address,City,ZIP,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [37]:
df2 = df.set_index("ID")
df2

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [40]:
df.set_index("ID", inplace=True)
df

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [43]:
df.set_index("Address", inplace=True, drop=False)
df

,Address,City,ZIP,Country,Name,Employees
Address,,,,,,
3666 21st St,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,332 Hill St,San Francisco,California 94114,USA,Super River,25
3995 23rd St,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
551 Alvarado St,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [46]:
df.set_index("Name", inplace=True, drop=False)
df

,Address,City,ZIP,Country,Name,Employees
Name,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [50]:
df.loc["Super River":"Sanchez", "Country":"Employees"]

            Country         Name  Employees
Name
Super River     USA  Super River         25
Ben's Shop      USA   Ben's Shop         10
Sanchez         USA      Sanchez         12

In [55]:
list(df.loc[:,"Employees"])

[8, 15, 25, 10, 12, 20]

In [57]:
df.iloc[2:5, 3:6]

            Country         Name  Employees
Name
Super River     USA  Super River         25
Ben's Shop      USA   Ben's Shop         10
Sanchez         USA      Sanchez         12