In [64]:
import os
os.listdir()

['supermarkets.xlsx',
 'supermarkets-commas.txt',
 '.ipynb_checkpoints',
 'data.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.ipynb',
 'supermarkets-semi-colons.txt']

In [65]:
import pandas

In [66]:
df=pandas.read_csv("supermarkets.csv")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [67]:
df=pandas.read_json("supermarkets.json")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [68]:
df=pandas.read_excel("supermarkets.xlsx",sheet_name=0)
df

,ID,Address,City,State,Country,Supermarket Name,Number of Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [69]:
df=pandas.read_csv("supermarkets-commas.txt")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [70]:
df=pandas.read_csv("supermarkets-semi-colons.txt", sep=";")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [71]:
df = pandas.read_csv("data.txt", header=None)
df

   0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [72]:
df.columns = ["ID", "Address", "City", "ZIP", "Country", "Name", "Employees"]
df

,ID,Address,City,ZIP,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [73]:
df.set_index("ID")

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [74]:
df

,ID,Address,City,ZIP,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [75]:
df2 = df.set_index("ID")
df2

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [76]:
df.set_index("ID", inplace=True)
df

,Address,City,ZIP,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [77]:
df.set_index("Address", inplace=True, drop=False)
df

,Address,City,ZIP,Country,Name,Employees
Address,,,,,,
3666 21st St,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,332 Hill St,San Francisco,California 94114,USA,Super River,25
3995 23rd St,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
551 Alvarado St,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [78]:
df.set_index("Name", inplace=True, drop=False)
df

,Address,City,ZIP,Country,Name,Employees
Name,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [79]:
df.loc["Super River":"Sanchez", "Country":"Employees"]

            Country         Name  Employees
Name
Super River     USA  Super River         25
Ben's Shop      USA   Ben's Shop         10
Sanchez         USA      Sanchez         12

In [80]:
list(df.loc[:,"Employees"])

[8, 15, 25, 10, 12, 20]

In [81]:
df.iloc[2:5, 3:6]

            Country         Name  Employees
Name
Super River     USA  Super River         25
Ben's Shop      USA   Ben's Shop         10
Sanchez         USA      Sanchez         12

In [82]:
df.iloc[3, :]

Address       3995 23rd St
City         San Francisco
ZIP               CA 94114
Country                USA
Name            Ben's Shop
Employees               10
Name: Ben's Shop, dtype: object

In [83]:
df_del = df
df_del

,Address,City,ZIP,Country,Name,Employees
Name,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [84]:
df_del.drop("City",axis=1)

                     Address               ZIP Country         Name  Employees
Name
Madeira         3666 21st St          CA 94114     USA      Madeira          8
Bready Shop   735 Dolores St          CA 94119     USA  Bready Shop         15
Super River      332 Hill St  California 94114     USA  Super River         25
Ben's Shop      3995 23rd St          CA 94114     USA   Ben's Shop         10
Sanchez      1056 Sanchez St        California     USA      Sanchez         12
Richvalley   551 Alvarado St          CA 94114     USA   Richvalley         20

In [85]:
df_del.drop("Madeira", axis=0)

,Address,City,ZIP,Country,Name,Employees
Name,,,,,,
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [86]:
df_del.index[0:3]

Index(['Madeira', 'Bready Shop', 'Super River'], dtype='str', name='Name')

In [87]:
df_del.columns[0:3]

Index(['Address', 'City', 'ZIP'], dtype='str')

In [88]:
df_del.drop(df_del.columns[0:3], axis=1)

            Country         Name  Employees
Name
Madeira         USA      Madeira          8
Bready Shop     USA  Bready Shop         15
Super River     USA  Super River         25
Ben's Shop      USA   Ben's Shop         10
Sanchez         USA      Sanchez         12
Richvalley      USA   Richvalley         20

In [89]:
df_del.iloc[0,3]

'USA'

In [90]:
df["Continent"] = df["Country"].apply(lambda x: "North America" if x == "USA" else "Other")
df

,Address,City,ZIP,Country,Name,Employees,Continent
Name,,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,North America
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,North America
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25,North America
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,North America
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,North America
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,North America

In [91]:
df["Continent"] = df["Country"] + " Continent"

In [92]:
df

,Address,City,ZIP,Country,Name,Employees,Continent
Name,,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,USA Continent
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,USA Continent
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25,USA Continent
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,USA Continent
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,USA Continent
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,USA Continent

In [93]:
df_t = df.T
df_t

Name,Madeira,Bready Shop,Super River,Ben's Shop,Sanchez,Richvalley
Address,3666 21st St,735 Dolores St,332 Hill St,3995 23rd St,1056 Sanchez St,551 Alvarado St
City,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco
ZIP,CA 94114,CA 94119,California 94114,CA 94114,California,CA 94114
Country,USA,USA,USA,USA,USA,USA
Name,Madeira,Bready Shop,Super River,Ben's Shop,Sanchez,Richvalley
Employees,8,15,25,10,12,20
Continent,USA Continent,USA Continent,USA Continent,USA Continent,USA Continent,USA Continent

In [94]:
df_t["My Shop Name"] = ["My Address", "My City", "My State", "My Country", "My Shop Name", "10", "My Continent"]
df_t

Name,Madeira,Bready Shop,Super River,Ben's Shop,Sanchez,Richvalley,My Shop Name
Address,3666 21st St,735 Dolores St,332 Hill St,3995 23rd St,1056 Sanchez St,551 Alvarado St,My Address
City,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,My City
ZIP,CA 94114,CA 94119,California 94114,CA 94114,California,CA 94114,My State
Country,USA,USA,USA,USA,USA,USA,My Country
Name,Madeira,Bready Shop,Super River,Ben's Shop,Sanchez,Richvalley,My Shop Name
Employees,8,15,25,10,12,20,10
Continent,USA Continent,USA Continent,USA Continent,USA Continent,USA Continent,USA Continent,My Continent

In [95]:
df = df_t.T
df

,Address,City,ZIP,Country,Name,Employees,Continent
Name,,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,USA Continent
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,USA Continent
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25,USA Continent
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,USA Continent
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,USA Continent
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,USA Continent
My Shop Name,My Address,My City,My State,My Country,My Shop Name,10,My Continent

In [96]:
import geopy
from geopy.geocoders import ArcGIS

In [97]:
nom=ArcGIS()
df.loc["Madeira","Address":"Country"]

Address     3666 21st St
City       San Francisco
ZIP             CA 94114
Country              USA
Name: Madeira, dtype: object

In [98]:
nom.geocode(df.loc["Madeira","Address":"Country"])

Location(3666 21st St, San Francisco, California, 94114, (37.75664822094, -122.429374802126, 0.0))

In [99]:
df["Latitude"] = (df["Address"] + "  , " + df["City"] + ", " + df["ZIP"]).apply(lambda x : nom.geocode(x).latitude)
df["Longitude"] = (df["Address"] + "  , " + df["City"] + ", " + df["ZIP"]).apply(lambda x : nom.geocode(x).longitude)
df

,Address,City,ZIP,Country,Name,Employees,Continent,Latitude,Longitude
Name,,,,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,USA Continent,37.756648,-122.429375
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,USA Continent,37.757811,-122.425493
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25,USA Continent,37.755842,-122.428836
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,USA Continent,37.752939,-122.431650
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,USA Continent,37.752131,-122.430028
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,USA Continent,37.753511,-122.433229
My Shop Name,My Address,My City,My State,My Country,My Shop Name,10,My Continent,9.913490,-84.538200

In [100]:
df

,Address,City,ZIP,Country,Name,Employees,Continent,Latitude,Longitude
Name,,,,,,,,,
Madeira,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,USA Continent,37.756648,-122.429375
Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,USA Continent,37.757811,-122.425493
Super River,332 Hill St,San Francisco,California 94114,USA,Super River,25,USA Continent,37.755842,-122.428836
Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,USA Continent,37.752939,-122.431650
Sanchez,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,USA Continent,37.752131,-122.430028
Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,USA Continent,37.753511,-122.433229
My Shop Name,My Address,My City,My State,My Country,My Shop Name,10,My Continent,9.913490,-84.538200